version: '3.8'

services:

  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: 'Y'
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
      MSSQL_SERVER: '192.168.0.106\SQLEXPRESS'
    ports:
      - 1433:1433
